world/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('worldapp.urls')),
]

worldapp/urls.py
from django.urls import path , re_path
from worldapp.views import *

app_name = 'worldapp'
urlpatterns = [
 path('world/',WorldListView.as_view(),name='world'),   
 re_path(r'^world/(?P<word>\w)/$',World_abcListView.as_view(), name='world'),
 path('world/<slug:country>/',CountryListView.as_view(),name='country'),
]

worldapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class City(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=35)  # Field name made lowercase.
    countrycode = models.ForeignKey('Country', models.DO_NOTHING, db_column='CountryCode')  # Field name made lowercase.
    district = models.CharField(db_column='District', max_length=20)  # Field name made lowercase.
    population = models.IntegerField(db_column='Population')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'city'
    def __str__(self):
        return self.name


class Country(models.Model):
    code = models.CharField(db_column='Code', primary_key=True, max_length=3)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=52)  # Field name made lowercase.
    continent = models.CharField(db_column='Continent', max_length=13)  # Field name made lowercase.
    region = models.CharField(db_column='Region', max_length=26)  # Field name made lowercase.
    surfacearea = models.FloatField(db_column='SurfaceArea')  # Field name made lowercase.
    indepyear = models.SmallIntegerField(db_column='IndepYear', blank=True, null=True)  # Field name made lowercase.
    population = models.IntegerField(db_column='Population')  # Field name made lowercase.
    lifeexpectancy = models.FloatField(db_column='LifeExpectancy', blank=True, null=True)  # Field name made lowercase.
    gnp = models.FloatField(db_column='GNP', blank=True, null=True)  # Field name made lowercase.
    gnpold = models.FloatField(db_column='GNPOld', blank=True, null=True)  # Field name made lowercase.
    localname = models.CharField(db_column='LocalName', max_length=45)  # Field name made lowercase.
    governmentform = models.CharField(db_column='GovernmentForm', max_length=45)  # Field name made lowercase.
    headofstate = models.CharField(db_column='HeadOfState', max_length=60, blank=True, null=True)  # Field name made lowercase.
    capital = models.IntegerField(db_column='Capital', blank=True, null=True)  # Field name made lowercase.
    code2 = models.CharField(db_column='Code2', max_length=2)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'country'
    def __str__(self):
        return self.name + ' ' + self.code


class Countrylanguage(models.Model):
    countrycode = models.ForeignKey(Country, models.DO_NOTHING, db_column='CountryCode', primary_key=True)  # Field name made lowercase.
    language = models.CharField(db_column='Language', max_length=30)  # Field name made lowercase.
    isofficial = models.CharField(db_column='IsOfficial', max_length=1)  # Field name made lowercase.
    percentage = models.FloatField(db_column='Percentage')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'countrylanguage'
        unique_together = (('countrycode', 'language'),)
    def __str__(self):
        return self.language

worldapp/views.py
from django.shortcuts import render
from django.views.generic import ListView
from worldapp.models import *

class WorldListView(ListView):
	model = Country
	queryset = Country.objects.order_by('name')

	def get_context_data(self,**kwargs):
		context = super(WorldListView, self).get_context_data(**kwargs)
		context['abc_menu'] = [chr(x) for x in range(65,91)]
		return context

class World_abcListView(ListView):
	model = Country
	
	def get_queryset(self):
		q = self.kwargs['word']
		return Country.objects.filter(name__istartswith= q).order_by('name')

	def get_context_data(self, **kwargs):
	    context = super(World_abcListView, self).get_context_data(**kwargs)
	    context['abc_menu'] = [chr(x) for x in range(65,91)]
	    return context

class CountryListView(ListView):
	model = Country
	template_name = 'worldapp/country.html'
	allow_empty = False

	def get_queryset(self):
		country = self.kwargs['country'].replace("-"," ")
		return Country.objects.filter(name=country)

	def get_context_data(self, **kwargs):
	    context = super(CountryListView, self).get_context_data(**kwargs)
	    context['abc_menu'] = [chr(x) for x in range(65,91)]
	    context['country'] = self.kwargs['country']
	    context['country_obj'] = Country.objects.get(name=self.kwargs['country'].replace("-"," "))
	    return context

worldapp/templates/worldapp/base.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<title>World</title>
</head>
<body class="bg-dark">

<h2 class="bg-dark text-center"><a class="text-success" href="{% url "worldapp:world" %}">World</a></h2>

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand text-success" href="{% url "worldapp:world" %}">All</a>
  {% for x in abc_menu %}
  <a class="navbar-brand text-success" href="{% url "worldapp:world" x %}">[{{ x }}]</a>
  {% endfor %}
</nav>

{% block content %} {% endblock %}

</body>
</html>

worldapp/templates/worldapp/country.html
{% extends 'worldapp/base.html' %}

{% block content  %}

<div class="alert alert-primary" role="alert">
	<h3 class="text-center">Detail information : {{ country_obj }} </h3>
</div>
<div class="table-responsive">
 	<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Population</th>
      <th scope="col">Surface Arena</th>
      <th scope="col">Continent</th>
      <th scope="col">Region</th>
      <th scope="col">Code</th>
      <th scope="col">President</th>
      <th scope="col">Indep Year</th>
      <th scope="col">Life Expectancy</th>
      <th scope="col">GNP</th>
      <th scope="col">GNP Old</th>
      <th scope="col">Local Name</th>
      <th scope="col">Government Form</th>
      <th scope="col">Capital</th>
      <th scope="col">Code2</th>
    </tr>
  </thead>
  <tbody>
  	
    <tr>
      <td>{{ country_obj.population }}</td>
      <td>{{ country_obj.surfacearea }}</td>
      <td>{{ country_obj.continent }}</td>
      <td>{{ country_obj.region }}</td>
      <td>{{ country_obj.code }}</td>
      <td>{{ country_obj.headofstate }}</td>
      <td>{{ country_obj.indepyear}}</td>
      <td>{{ country_obj.lifeexpectancy }}</td>
      <td>{{ country_obj.gnp }}</td>
      <td>{{ country_obj.gnpold }}</td>
      <td>{{ country_obj.localname }}</td>
      <td>{{ country_obj.governmentform }}</td>
      <td>{{ country_obj.capital }}</td>
      <td>{{ country_obj.code2 }}</td>
    </tr>
  </tbody>
</table>
</div>

<div class="alert alert-danger text-center" >
  <h3>Languages of {{ country_obj.name }}</h3>
</div>

<div class="table-responsive">
 	<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Language</th>
      <th scope="col">Is Official</th>
      <th scope="col">Procentage</th>
      
    </tr>
  </thead>
  <tbody>
  	{% for x in country_obj.countrylanguage_set.all %}
    <tr>

      <td>{{ x.language }}</td>
      <td>{% if x.isofficial == "T" %} YES {% elif x.isofficial == 'F' %} NO {% endif %} </td>
      <td>{{ x.percentage }}</td>
      
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>

<div class="alert alert-success text-center" >
  <h3>City of {{ country_obj.name }} : ({{ country_obj.city_set.all.count }})</h3>
</div>

<div class="table-responsive">
 	<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Country Code</th>
      <th scope="col">District</th>
      <th scope="col">Population</th>
      
    </tr>
  </thead>
  <tbody>
  	{% for x in country_obj.city_set.all %}
    <tr>
      <td>{{ x.name }}</td>
      <td>{{ x.countrycode }}</td>
      <td>{{ x.district }}</td>
      <td>{{ x.population }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>

{% endblock %}

worldapp/templates/worldapp/country_list.html
{% extends "worldapp/base.html" %}

{% block content %} 

<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Population</th>
      <th scope="col">Surface Arena</th>
      <th scope="col">Continent</th>
      <th scope="col">Region</th>
      <th scope="col">Code</th>
      <th scope="col">President</th>
    </tr>
  </thead>
  <tbody>
  	{% if object_list %}
    {% for x in object_list%}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url "worldapp:country" x.name|slugify %}"> {{ x.name }}</a></td>
      <td>{{ x.population }}</td>
      <td>{{ x.surfacearea }}</td>
      <td>{{ x.continent }}</td>
      <td>{{ x.region }}</td>
      <td>{{ x.code }}</td>
      <td>{{ x.headofstate }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <h3 class="text-warning text-center">None</h3>
    {% endif %}
  </tbody>
</table>


{% endblock %}